version: '3.8'
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
      # Use a named volume for node_modules to avoid overwriting with the host's node_modules
      - node_modules:/app/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

volumes:
  node_modules: 